### PR TITLE
Merge pull request #1 from abhi18av/master

### PR DESCRIPTION
**Pull request by abyla1**
Added "x" mark to all [ ]

### CODE REVIEW

**Comment by abhi18av** [comment]
Abylai, there are no files changed. 

So, it's good that you've sent me the merge request but you must add `X` in your `[ ]` for the `TaskList-1`

For example,

`[x] some-task`

**Comment by abhi18av** [comment]
@abyla1 , please complete the tasks and then add the pull request from your master.

**Comment by abyla1** [comment]
I'm feeling so stupid  now

**Comment by abhi18av** [comment]
Don't feel stupid @abyla1 !

It took me so much time to learn and you can already do it :+1:

**Comment by abyla1** [comment]
We did it? yeaaaah!

**Comment by abhi18av** [comment]
Yup!

**Pull request merged**
